# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirstStartApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'Alamofire'
pod 'SwiftyJSON'

end
